// Text extraction utilities for translation

export interface PageTexts {
  [pageName: string]: {
    key: string;
    original: string;
    context?: string;
  }[];
}

export const pageTexts: PageTexts = {
  home: [
    { key: 'header.button', original: 'Customer Intelligence AI Agents', context: 'Header navigation button' },
    { key: 'hero.subtitle1', original: 'Consumer Good', context: 'Hero section subtitle part 1' },
    { key: 'hero.subtitle2', original: 'Brands', context: 'Hero section subtitle part 2' },
    { key: 'hero.title', original: 'Get 1M-100M views in 90 days on social media', context: 'Hero section main title' },
    { key: 'hero.description_prefix', original: 'Backed by our Viral Content Research Lab, the system behind over ', context: 'Hero section description prefix' },
    { key: 'hero.views', original: '6 billion views', context: 'Hero section views count' },
    { key: 'hero.description_mid', original: ' and ', context: 'Hero section description middle' },
    { key: 'hero.followers', original: '24 million followers', context: 'Hero section followers count' },
    { key: 'hero.cta', original: 'Dominate Social Media', context: 'Hero call-to-action button' },
    { key: 'video.alt', original: 'Digicon Pro Showreel 2025 Video Thumbnail', context: 'Video thumbnail alt text' },
    { key: 'video.title', original: 'Digicon Pro Showreel 2025 Video', context: 'Video iframe title' },
    { key: 'value.title_prefix', original: 'Use maximum content distribution to ', context: 'Value title prefix' },
    { key: 'value.title_highlight', original: ' dominate social media', context: 'Value title highlight' },
    { key: 'value.stat1.val', original: '1/25th', context: 'Value stat 1 value' },
    { key: 'value.stat1.label', original: 'Cost of Ads', context: 'Value stat 1 label' },
    { key: 'value.stat2.val', original: 'Limited', context: 'Value stat 2 value' },
    { key: 'value.stat2.label', original: 'Spots', context: 'Value stat 2 label' },
    { key: 'value.stat3.val', original: 'Fully', context: 'Value stat 3 value' },
    { key: 'value.stat3.label', original: 'Compliant', context: 'Value stat 3 label' },
    { key: 'value.stats.prefix', original: "We've generated over ", context: 'Value stats prefix' },
    { key: 'value.stats.views_count', original: '6 billion organic views ', context: 'Value stats views count' },
    { key: 'value.stats.suffix', original: ' in less than 2 years with our proprietary Viral Content Research Lab.', context: 'Value stats suffix' },
    { key: 'value.listTitle', original: 'Work with us to:', context: 'Value proposition list title' },
    { key: 'value.item1', original: 'Have the fastest way to grow on social media today', context: 'Value proposition item 1' },
    { key: 'value.item2', original: 'Scale brands to post 100+ times per month', context: 'Value proposition item 2' },
    { key: 'value.item3', original: 'Get in front of millions more of the right people', context: 'Value proposition item 3' },
    { key: 'value.item4', original: 'Ensure top-quality across all the content posted', context: 'Value proposition item 4' },
    { key: 'value.cta', original: 'Talk to us', context: 'Value section CTA button' },
    { key: 'showcase.title_prefix', original: "(Just some) content we've ", context: 'Showcase title prefix' },
    { key: 'showcase.title_highlight', original: 'created', context: 'Showcase title highlight' },
    { key: 'problem.title_prefix', original: 'Most consumer good brands are generating a ', context: 'Problem title prefix' },
    { key: 'problem.title_highlight', original: ' small fraction', context: 'Problem title highlight' },
    { key: 'problem.title_suffix', original: ' of the potential growth from their organic content.', context: 'Problem title suffix' },
    { key: 'problem.subtitle', original: '(Even if you already have an audience in the millions)', context: 'Problem section subtitle' },
    { key: 'problem.description', original: 'This results in dramatically less exposure and growth for your brand.', context: 'Problem section description' },
    { key: 'problem.cta_text', original: 'You deserve more for your efforts.', context: 'Problem section CTA text' },
    { key: 'brands.title_prefix', original: 'Brands that have ', context: 'Brands title prefix' },
    { key: 'brands.title_highlight', original: 'grown', context: 'Brands title highlight' },
    { key: 'brands.title_suffix', original: ' with us', context: 'Brands title suffix' },
    { key: 'recognition.title_prefix', original: 'Recognized by ', context: 'Recognition title prefix' },
    { key: 'recognition.title_highlight', original: 'publications ', context: 'Recognition title highlight' },
    { key: 'recognition.title_suffix', original: ' as the #1 leading firm in social media growth', context: 'Recognition title suffix' },
    { key: 'how.title_prefix', original: 'How does it ', context: 'How title prefix' },
    { key: 'how.title_highlight', original: 'work?', context: 'How title highlight' },
    { key: 'how.subtitle_prefix', original: 'Data-driven success formula discovery through our ', context: 'How subtitle prefix' },
    { key: 'how.subtitle_highlight', original: '"Viral Content Research Lab"', context: 'How subtitle highlight' },
    { key: 'how.step1.title', original: 'Idea Generation', context: 'How it works step 1 title' },
    { key: 'how.step1.desc', original: 'We analyze the latest TikTok trends, Gen Z interests, and competitor content daily to create a constant source of fresh ideas.', context: 'How it works step 1 description' },
    { key: 'how.step2.title', original: 'Rapid Testing', context: 'How it works step 2 title' },
    { key: 'how.step2.desc', original: 'Generated ideas are uploaded to private test channels to gauge immediate consumer reactions and feedback.', context: 'How it works step 2 description' },
    { key: 'how.step3.title', original: 'Data Validation', context: 'How it works step 3 title' },
    { key: 'how.step3.desc', original: 'We objectively determine \'success\' and \'failure\' using clear metrics: views, comments, and share rates.', context: 'How it works step 3 description' },
    { key: 'how.step4.title', original: 'Success Formula Scaling', context: 'How it works step 4 title' },
    { key: 'how.step4.desc', original: 'We intensively utilize the format and key elements of verified \'hit videos\' to maximize viral impact.', context: 'How it works step 4 description' },
    { key: 'how.approach.title', original: 'Our Proven Approach', context: 'Proven approach section title' },
    { key: 'how.approach.item1.title', original: 'Minimize uncertainty', context: 'Proven approach item 1 title' },
    { key: 'how.approach.item1.desc', original: ' and execute only the highest probability marketing strategies', context: 'Proven approach item 1 description' },
    { key: 'how.approach.item2.title', original: 'Collect feedback', context: 'Proven approach item 2 title' },
    { key: 'how.approach.item2.desc', original: ' from small target groups and analyze rapidly', context: 'Proven approach item 2 description' },
    { key: 'how.approach.item3.title', original: 'Repeatedly apply', context: 'Proven approach item 3 title' },
    { key: 'how.approach.item3.desc', original: ' verified success formulas to maximize marketing efficiency', context: 'Proven approach item 3 description' },
    { key: 'how.compliance_prefix', original: 'Yes, this is ', context: 'Compliance prefix' },
    { key: 'how.compliance_highlight', original: 'fully compliant ', context: 'Compliance highlight' },
    { key: 'how.compliance_suffix', original: 'across each social media platform.', context: 'Compliance suffix' },
    { key: 'results.title_prefix', original: "Results we've ", context: 'Results title prefix' },
    { key: 'results.title_highlight', original: 'generated', context: 'Results title highlight' },
    { key: 'results.stat1.val', original: '6B+', context: 'Results stat 1 value' },
    { key: 'results.stat1.desc', original: 'Views generated on social platforms', context: 'Results stat 1 description' },
    { key: 'results.stat2.val', original: '24M+', context: 'Results stat 2 value' },
    { key: 'results.stat2.desc', original: 'Followers gained for our clients', context: 'Results stat 2 description' },
    { key: 'results.stat3.val', original: '137M+', context: 'Results stat 3 value' },
    { key: 'results.stat3.desc', original: 'Followers reached through top brands', context: 'Results stat 3 description' },
    { key: 'results.stat4.val', original: '20,300+', context: 'Results stat 4 value' },
    { key: 'results.stat4.desc', original: 'Pieces of content published per month', context: 'Results stat 4 description' },
    { key: 'results.stat5.val', original: '85+', context: 'Results stat 5 value' },
    { key: 'results.stat5.desc', original: 'Expert team members', context: 'Results stat 5 description' },
    { key: 'results.stat6.val', original: '450+', context: 'Results stat 6 value' },
    { key: 'results.stat6.desc', original: 'Years of combined experience', context: 'Results stat 6 description' },
    { key: 'results.cta_text', original: 'Want to learn if we are a fit to scale your brand?', context: 'Results section CTA text' },
    { key: 'platforms.title_prefix', original: 'Become ', context: 'Platforms title prefix' },
    { key: 'platforms.title_highlight', original: 'omnipresent', context: 'Platforms title highlight' },
    { key: 'platforms.title_suffix', original: ' on our expert platforms', context: 'Platforms title suffix' },
    { key: 'platforms.cta_text', original: 'Want to learn more?', context: 'Platforms section CTA text' },
    { key: 'footer.cta', original: 'Ready to dominate social media?', context: 'Footer CTA text' },
    { key: 'footer.rights_prefix', original: '© ', context: 'Footer copyright prefix' },
    { key: 'footer.rights_suffix', original: ' Digicon Pro. All rights reserved.', context: 'Footer copyright suffix' },
  ],
  'creative-intelligence-agent-beauty': [
    { key: 'header.button', original: 'Visibility Scaling AI Agents', context: 'Header navigation button' },
    { key: 'overlay.title', original: 'Choose Your Business Type', context: 'Overlay title' },
    { key: 'overlay.description', original: 'Select the type of business you\'re looking for solutions for:', context: 'Overlay description' },
    { key: 'overlay.select_placeholder', original: 'Select business type', context: 'Dropdown placeholder' },
    { key: 'overlay.option.beauty', original: 'Beauty', context: 'Beauty option' },
    { key: 'overlay.option.other', original: 'Other', context: 'Other option' },
    { key: 'tagline', original: 'AI-Powered Market Entry / Brand Acceleration / Brand Authority for Korean Beauty Brands', context: 'Header tagline' },
    { key: 'hero.title', original: 'Stop Paying Booking Fees To Skeptical Influencers. Build Trust Signals First.', context: 'Hero title' },
    { key: 'hero.subtitle', original: 'We deploy our intelligence engines technology to create up to 50 high-quality videos per month that make you LOOK like a brand worth betting on, then mine proof of customer demand from real engagement, so you can approach KOCs with leverage and good commission deals instead of hope.', context: 'Hero subtitle' },
    { key: 'hero.cta1', original: 'Apply for Access', context: 'Primary CTA' },
    { key: 'hero.cta2', original: 'See how it works', context: 'Secondary CTA' },
    { key: 'social.revenue.impact', original: 'Revenue Impact', context: 'Revenue Impact label' },
    { key: 'social.revenue.sub', original: 'Attributed via optimization', context: 'Revenue Impact subtext' },
    { key: 'social.organic.views', original: 'Organic Views', context: 'Organic Views label' },
    { key: 'social.organic.sub', original: 'Across social media', context: 'Organic Views subtext' },
    { key: 'social.adspend.managed', original: 'Ad Spend Managed', context: 'Ad Spend Managed label' },
    { key: 'social.adspend.sub', original: 'Optimized by our team', context: 'Ad Spend Managed subtext' },
    { key: 'social.campaigns.title', original: 'Campaigns', context: 'Campaigns label' },
    { key: 'social.campaigns.sub', original: 'Successful launches', context: 'Campaigns subtext' },
    { key: 'fit.for.title', original: 'This Is For You If:', context: 'Fit filter For title' },
    { key: 'fit.for.item1', original: 'Quality KOCs ignore your DMs or quote booking fees that would eat your entirely monthly budget', context: 'Fit filter For item 1' },
    { key: 'fit.for.item2', original: 'You’ve spent tens of thousands on influencers and social media, but cannot point to single repeatable pattern that drive results', context: 'Fit filter For item 2' },
    { key: 'fit.for.item3', original: 'You sense that Vietnamese consumers are changing fast but you do not know how to respond to them', context: 'Fit filter For item 3' },
    { key: 'fit.for.item4', original: 'You’ve had viral moments that felt like luck but you can’t replicate them', context: 'Fit filter For item 4' },
    { key: 'fit.for.item5', original: 'You’re entering or expanding in US and Vietnam/SEA with a real product, real e-commerce site, and need to learn what works fast', context: 'Fit filter For item 5' },
    { key: 'fit.not.title', original: 'Not For You If:', context: 'Fit filter Not title' },
    { key: 'fit.not.item1', original: 'You want a few videos with no testing, no irritation, no learning loop', context: 'Fit filter Not item 1' },
    { key: 'fit.not.item2', original: 'You’re happy with one-time campaigns and do not need a sustainable playbook', context: 'Fit filter Not item 2' },
    { key: 'fit.not.item3', original: 'You expect guaranteed revenue from day one without needing a scaling system', context: 'Fit filter Not item 3' },
    { key: 'fit.not.item4', original: 'You’re domestic-only and offline-first with no interest in international expansion', context: 'Fit filter Not item 4' },
    { key: 'fit.not.item5', original: 'You want to hide the fact that AI was used (we believe in transparent "Tech-Beauty" positioning)', context: 'Fit filter Not item 5' },
    { key: 'frame.title', original: 'The $2.7B Vietnam Market You Can See But Can’t Enter', context: 'Frame section title' },
    { key: 'frame.subtitle', original: 'You know the opportunity in Vietnam’s $2.74B and growing beauty market is real, but between you and that market is a wall called trust.', context: 'Frame section subtitle' },
    { key: 'frame.item1.title', original: 'Influencer Inflation Trap', context: 'Frame item 1 title' },
    { key: 'frame.item1.desc', original: 'Mega-influencers now can cost $20k+ (20-40x increase since 2022) with untrackable ROI. Your budget buys less reach each quarter.', context: 'Frame item 1 description' },
    { key: 'frame.item2.title', original: 'The Trust Collapse', context: 'Frame item 2 title' },
    { key: 'frame.item2.desc', original: 'Vietnamese consumers now assume “unproven = potential scam” due to the rise of counterfeit creams and deepfakes. Views no longer equal consideration.', context: 'Frame item 2 description' },
    { key: 'frame.item3.title', original: 'KOCs Rejection Loop', context: 'Frame item 3 title' },
    { key: 'frame.item3.desc', original: 'Quality KOCs who actually drive sales will not risk their reputation on unknown brands. They either ghost you, demand prohibitive booking fees or give you their B-tier effort.', context: 'Frame item 3 description' },
    { key: 'frame.item4.title', original: 'The 2026 Cliff', context: 'Frame item 4 title' },
    { key: 'frame.item4.desc', original: 'Vietnam’s new Advertising Law (Jan 2026) makes KOCs personally liable for product claims. KOCs who were already cautious will become extremely selective.', context: 'Frame item 4 description' },
    { key: 'frame.item5.title', original: 'Zero Leverage', context: 'Frame item 5 title' },
    { key: 'frame.item5.desc', original: 'You’re renting attention instead of building. Each campaign starts from zero. No compounding learning, no leverage for the next negotiation.', context: 'Frame item 5 description' },
    { key: 'mechanism.title', original: 'How to Break the Rejection Cycle', context: 'Mechanism section title' },
    { key: 'mechanism.subtitle', original: 'KOCs won’t work with you because you look unproven, and you can’t prove demand because KOCs won’t work with you.', context: 'Mechanism section subtitle' },
    { key: 'mechanism.table.header1', original: 'What you need', context: 'Mechanism table header 1' },
    { key: 'mechanism.table.header2', original: 'How we deliver it', context: 'Mechanism table header 2' },
    { key: 'mechanism.row1.col1', original: 'A “big brand energy” at 10% of the cost', context: 'Mechanism row 1 col 1' },
    { key: 'mechanism.row1.col2', original: 'High-quality AI product visualization makes you LOOK like a brand that has already invested millions', context: 'Mechanism row 1 col 2' },
    { key: 'mechanism.row2.col1', original: 'Direct buying signals', context: 'Mechanism row 2 col 1' },
    { key: 'mechanism.row2.col2', original: '30-50 videos per month that harvest intent comments which show PROOF of demand that you take to KOCs', context: 'Mechanism row 2 col 2' },
    { key: 'mechanism.row3.col1', original: 'The leverage to negotiate', context: 'Mechanism row 3 col 1' },
    { key: 'mechanism.row3.col2', original: 'The proof “500 people are already asking to buy” you receive from us changes the conversation from begging to offering', context: 'Mechanism row 3 col 2' },
    { key: 'mechanism.row4.col1', original: '2026 compliance handled', context: 'Mechanism row 4 col 1' },
    { key: 'mechanism.row4.col2', original: 'Compliance documentation that satisfies KOC legal requirements', context: 'Mechanism row 4 col 2' },
    { key: 'mechanism.footer', original: 'AI opens the door. KOCs close the sale.', context: 'Mechanism section footer' },
    { key: 'protocol.title', original: '3 Months From Being Unknown to Trustworthy', context: 'Protocol title' },
    { key: 'protocol.phase1.title', original: 'PHASE 1: THE TRUST BASE (Month 1)', context: 'Protocol phase 1 title' },
    { key: 'protocol.phase1.subtitle', original: 'Look like a brand worth partnering with', context: 'Protocol phase 1 subtitle' },
    { key: 'protocol.phase1.desc', original: 'We produce 10 high-end AI product-focused visualization videos that signal investment, quality control, and premium positioning. We also set up verified official accounts (Zalo OA, TikTok) for credibility.', context: 'Protocol phase 1 description' },
    { key: 'protocol.phase1.outcome', original: 'Outcome: You pass the “first impression” test that currently fails.', context: 'Protocol phase 1 outcome' },
    { key: 'protocol.phase2.title', original: 'PHASE 2: SIGNAL MINING (Months 1-2)', context: 'Protocol phase 2 title' },
    { key: 'protocol.phase2.subtitle', original: 'Harvest proof of demand.', context: 'Protocol phase 2 subtitle' },
    { key: 'protocol.phase2.desc', original: 'We deploy 30-50 AI-generated shorts per month using trending audio and localized hooks – not to have vanity views, but to mine and categorize buying-signal data from comments.', context: 'Protocol phase 2 description' },
    { key: 'protocol.phase2.outcome', original: 'Outcome: You have documented evidence that real people want to buy.', context: 'Protocol phase 2 outcome' },
    { key: 'protocol.phase3.title', original: 'PHASE 3: THE DATA-DRIVEN PITCH (Month 3)', context: 'Protocol phase 3 title' },
    { key: 'protocol.phase3.subtitle', original: 'Change the negotiation.', context: 'Protocol phase 3 subtitle' },
    { key: 'protocol.phase3.desc', original: 'Now you approach KOCs with a different script: "We have 500 people asking where to buy. You take the commission." You\'re offering them a deal instead of begging them to take the risk.', context: 'Protocol phase 3 description' },
    { key: 'protocol.phase3.outcome', original: 'Outcome: Commission-only partnerships. No booking fees. Aligned incentives.', context: 'Protocol phase 3 outcome' },
    { key: 'protocol.phase4.title', original: 'PHASE 4: VERIFICATION & CONVERSION (Month 3)', context: 'Protocol phase 4 title' },
    { key: 'protocol.phase4.subtitle', original: 'Make it real.', context: 'Protocol phase 4 subtitle' },
    { key: 'protocol.phase4.desc', original: 'AI opened the door, KOCs closed the sale. They post "real skin" reviews that validate what the earlier high-quality videos promised, and content links directly to TikTok Shop or Zalo Mini App.', context: 'Protocol phase 4 description' },
    { key: 'protocol.phase4.outcome', original: 'Outcome: Sustainable system where AI generates leads and KOCs convert them.', context: 'Protocol phase 4 outcome' },
    { key: 'vs.title', original: 'Why Digicon approach?', context: 'Comparison title' },
    { key: 'vs.header1', original: 'THE OLD WAY', context: 'Comparison header 1' },
    { key: 'vs.header2', original: 'SIGNAL-FIRST APPROACH', context: 'Comparison header 2' },
    { key: 'vs.row1.old', original: 'Contact KOCs, get ghosted or rejected', context: 'Comparison row 1 old' },
    { key: 'vs.row1.new', original: 'Build visual authority first with AI', context: 'Comparison row 1 new' },
    { key: 'vs.row2.old', original: 'Pay $20k+ booking fees upfront (fixed cost)', context: 'Comparison row 2 old' },
    { key: 'vs.row2.new', original: 'Deploy 30-50 high-quality video variants/ month at 10% of the cost', context: 'Comparison row 2 new' },
    { key: 'vs.row3.old', original: 'Post content, pray it converts', context: 'Comparison row 3 old' },
    { key: 'vs.row3.new', original: 'Mine verified buying signals from real engagement', context: 'Comparison row 3 new' },
    { key: 'vs.row4.old', original: 'Gain only vanity metrics and pure guesswork', context: 'Comparison row 4 old' },
    { key: 'vs.row4.new', original: 'Approach KOC with proof of demand', context: 'Comparison row 4 new' },
    { key: 'vs.row5.old', original: 'Hire more KOCs until something clicks', context: 'Comparison row 5 old' },
    { key: 'vs.row5.new', original: 'Negotiate commission-only deals (aligned incentives)', context: 'Comparison row 5 new' },
    { key: 'vs.row6.old', original: 'Repeat with no learning and leverage', context: 'Comparison row 6 old' },
    { key: 'vs.row6.new', original: 'Stack validated learnings, KOCs verify, both win', context: 'Comparison row 6 new' },
    { key: 'honesty.title', original: 'Honesty Box', context: 'Honesty box title' },
    { key: 'honesty.promise.title', original: 'What We Promise', context: 'Honesty box promise title' },
    { key: 'honesty.promise.item1', original: 'Proven AI product visualization format that generates views and passes the legitimacy test', context: 'Honesty box promise item 1' },
    { key: 'honesty.promise.item2', original: 'Captured buying signals from real audience engagement', context: 'Honesty box promise item 2' },
    { key: 'honesty.promise.item3', original: 'Negotiation leverage to shift from booking fees to commission deals', context: 'Honesty box promise item 3' },
    { key: 'honesty.promise.item4', original: '2026-compliant documentation KOCs legally require', context: 'Honesty box promise item 4' },
    { key: 'honesty.not.title', original: 'What We Don’t Promise', context: 'Honesty box not promise title' },
    { key: 'honesty.not.item1', original: 'Guaranteed revenue numbers (as we deliver visibility and leverage)', context: 'Honesty box not promise item 1' },
    { key: 'honesty.not.item2', original: 'KOCs will definitely say yes (we give you the best possible position, you still pitch)', context: 'Honesty box not promise item 2' },
    { key: 'honesty.not.item3', original: 'Overnight results (this is a system, not a hack)', context: 'Honesty box not promise item 3' },
    { key: 'final.title', original: 'Stop Chasing KOCs. Start Attracting Them.', context: 'Final CTA title' },
    { key: 'final.from_to.title', original: 'In 3 months, your brands go', context: 'Final from-to title' },
    { key: 'final.from_to.header1', original: 'From', context: 'Final from-to header 1' },
    { key: 'final.from_to.header2', original: 'To', context: 'Final from-to header 2' },
    { key: 'final.from_to.row1.from', original: '“We are guessing what works”', context: 'Final from-to row 1 from' },
    { key: 'final.from_to.row1.to', original: '“We have intent data showing real buying signals, plus validated creative patterns that can be replicated”', context: 'Final from-to row 1 to' },
    { key: 'final.from_to.row2.from', original: '“Our customer data is stale”', context: 'Final from-to row 2 from' },
    { key: 'final.from_to.row2.to', original: '“We know what they’re asking, objecting, wanting right now”', context: 'Final from-to row 2 to' },
    { key: 'final.from_to.row3.from', original: '“KOCs ghost us”', context: 'Final from-to row 3 from' },
    { key: 'final.from_to.row3.to', original: '“KOCs see us as a good deal”', context: 'Final from-to row 3 to' },
    { key: 'final.from_to.row4.from', original: 'Gambling on attention each campaign', context: 'Final from-to row 4 from' },
    { key: 'final.from_to.row4.to', original: 'Building a repeatable, proven growth system', context: 'Final from-to row 4 to' },
    { key: 'final.from_to.row5.from', original: 'Paying $20,000 booking fees', context: 'Final from-to row 5 from' },
    { key: 'final.from_to.row5.to', original: 'Offering commission-only partnerships', context: 'Final from-to row 5 to' },
    { key: 'final.description', original: 'If you want influencer posts, hire an agency. If you want an AI-enabled brand acceleration system that makes quality KOCs want to work with you on commission, let\'s talk.', context: 'Final CTA description' },
    { key: 'final.cta', original: 'Apply for Access', context: 'Final CTA button' },
    { key: 'final.footer', original: 'We\'ll tell you quickly if this is a fit. Either way, you leave with clarity.', context: 'Final CTA footer' },
    { key: 'footer.rights', original: 'Digicon Pro. All rights reserved.', context: 'Footer rights' },
  ],
  'creative-intelligence-agent-other': [
    { key: 'header.button', original: 'Visibility Scaling AI Agents', context: 'Header navigation button' },
    { key: 'overlay.title', original: 'Choose Your Business Type', context: 'Overlay title' },
    { key: 'overlay.description', original: 'Select the type of business you\'re looking for solutions for:', context: 'Overlay description' },
    { key: 'overlay.select_placeholder', original: 'Select business type', context: 'Dropdown placeholder' },
    { key: 'overlay.option.beauty', original: 'Beauty', context: 'Beauty option' },
    { key: 'overlay.option.other', original: 'Other', context: 'Other option' },
    { key: 'hero.tag', original: 'Creative Intelligence Agents', context: 'Hero section tag' },
    { key: 'hero.title', original: 'Stop Paying Influencers to Improvise. Build Agents You Own.', context: 'Hero section main title' },
    { key: 'hero.subtitle', original: 'We deploy Creative Intelligence AI Agents that mine your first‑party data, ship controlled creative variants fast, and convert winners into Validated Creative Plays you can scale.', context: 'Hero section subtitle' },
    { key: 'hero.cta1', original: 'Apply for Access', context: 'Primary CTA button' },
    { key: 'hero.cta2', original: 'See how it works', context: 'Secondary CTA button' },
    { key: 'social.revenue.impact', original: 'Revenue Impact', context: 'Social proof revenue impact' },
    { key: 'social.revenue.sub', original: 'Attributed via optimization', context: 'Social proof revenue impact sub' },
    { key: 'social.organic.views', original: 'Organic Views', context: 'Social proof organic views' },
    { key: 'social.organic.sub', original: 'Across social media', context: 'Social proof organic views sub' },
    { key: 'social.adspend.managed', original: 'Ad Spend Managed', context: 'Social proof ad spend managed' },
    { key: 'social.adspend.sub', original: 'Optimized by our team', context: 'Social proof ad spend managed sub' },
    { key: 'social.campaigns.title', original: 'Campaigns', context: 'Social proof campaigns title' },
    { key: 'social.campaigns.sub', original: 'Successful launches', context: 'Social proof campaigns sub' },
    { key: 'fit.tag', original: 'Fit Filter', context: 'Fit filter tag' },
    { key: 'fit.title', original: 'Who This Is For (and Who It\'s Not)', context: 'Fit filter title' },
    { key: 'fit.for.title', original: 'This Is For You If:', context: 'Fit filter for title' },
    { key: 'fit.for.item1', original: 'You’ve spent tens of thousands on influencers and social media, but cannot point to single repeatable pattern that drive results', context: 'Fit filter for item 1' },
    { key: 'fit.for.item2', original: 'You sense that Vietnamese consumers are changing fast but you do not know how to respond', context: 'Fit filter for item 2' },
    { key: 'fit.for.item3', original: 'You’ve had viral moments that felt like luck but you can’t replicate them sustainably', context: 'Fit filter for item 3' },
    { key: 'fit.for.item4', original: 'You’re entering or expanding in Vietnam/SEA with a real product, real e-commerce site, and need to learn what works fast', context: 'Fit filter for item 4' },
    { key: 'fit.not.title', original: 'Not For:', context: 'Fit filter not for title' },
    { key: 'fit.not.item1', original: 'You want a few videos with no testing, no irritation, no learning loop', context: 'Fit filter not for item 1' },
    { key: 'fit.not.item2', original: 'You’re happy with one-time campaigns and do not need a sustainable playbook', context: 'Fit filter not for item 2' },
    { key: 'fit.not.item3', original: 'You expect guaranteed revenue from day one without needing a scaling system', context: 'Fit filter not for item 3' },
    { key: 'fit.not.item4', original: 'You’re domestic-only and offline-first with no interest in international expansion', context: 'Fit filter not for item 4' },
    { key: 'fit.not.item5', original: 'You want to hide the fact that AI was used (we believe transparency is the key to trust)', context: 'Fit filter not for item 5' },
    { key: 'shift.tag', original: 'Market Context', context: 'Market shift section tag' },
    { key: 'shift.title', original: 'Our Creative Marketing World has Changed Drastically', context: 'Market shift section title' },
    { key: 'shift.item1', original: 'Distribution is now mediated by AI platforms', context: 'Market shift item 1' },
    { key: 'shift.item2', original: 'Visibility used to come from people, now it comes from the algorithm', context: 'Market shift item 2' },
    { key: 'shift.item3', original: 'Advantage shifts from "more content" to structured data + algorithmic optimization', context: 'Market shift item 3' },
    { key: 'shift.item4', original: 'The buyer journey compresses toward instant, zero-click decisions', context: 'Market shift item 4' },
    { key: 'shift.item5', original: 'Trust still matters, but velocity determines who earns it first', context: 'Market shift item 5' },
    { key: 'shift.conclusion', original: 'The real problem behind failing campaigns is not “low views", but variance and lack of accumulated learning that create cost.', context: 'Market shift conclusion' },
    { key: 'problem.tag', original: 'The Problem', context: 'Problem section tag' },
    { key: 'problem.title', original: 'The "Creativity Gap" Is Quietly Taxing Every Campaign You Run.', context: 'Problem section title' },
    { key: 'problem.description', original: 'Visibility used to come from people. Now it comes from the feed. When brands outsource creative direction without capturing learnings, they keep paying for the same lessons again and again.', context: 'Problem section description' },
    { key: 'problem.item1.title', original: 'Too Many Messages', context: 'Problem item 1 title' },
    { key: 'problem.item1.desc', original: 'Diluted core value proposition.', context: 'Problem item 1 description' },
    { key: 'problem.item2.title', original: 'Too Little Truth', context: 'Problem item 2 title' },
    { key: 'problem.item2.desc', original: 'Content that feels like \'ads\' gets skipped.', context: 'Problem item 2 description' },
    { key: 'problem.item3.title', original: 'High Variance', context: 'Problem item 3 title' },
    { key: 'problem.item3.desc', original: 'No system to turn outcomes into decisions.', context: 'Problem item 3 description' },
    { key: 'problem.footer', original: 'We\'re not anti‑creator. We\'re anti‑improv. We separate what must scale from what must be earned.', context: 'Problem footer text' },
    { key: 'solution.tag', original: 'The Protocol', context: 'Solution protocol tag' },
    { key: 'solution.title', original: 'How Our AI Agents Turn Data Into Validated Creative Plays', context: 'Solution protocol title' },
    { key: 'solution.phase1.id', original: 'Phase 1', context: 'Solution phase 1 ID' },
    { key: 'solution.phase1.title', original: 'Customer Decision Intelligence Map', context: 'Solution phase 1 title' },
    { key: 'solution.phase1.goal', original: 'Know what makes your customer act before you scale.', context: 'Solution phase 1 goal' },
    { key: 'solution.phase1.output1', original: 'Market Message Map', context: 'Solution phase 1 output 1' },
    { key: 'solution.phase1.output2', original: 'Objection Library', context: 'Solution phase 1 output 2' },
    { key: 'solution.phase1.output3', original: 'First Hypothesis Set', context: 'Solution phase 1 output 3' },
    { key: 'solution.phase2.id', original: 'Phase 2', context: 'Solution phase 2 ID' },
    { key: 'solution.phase2.title', original: 'AI‑Accelerated Throughput Engine', context: 'Solution phase 2 title' },
    { key: 'solution.phase2.goal', original: 'Produce enough high-quality variants to learn fast.', context: 'Solution phase 2 goal' },
    { key: 'solution.phase2.output1', original: 'Monthly Creative Cadence', context: 'Solution phase 2 output 1' },
    { key: 'solution.phase2.output2', original: 'Whitelisting Setups', context: 'Solution phase 2 output 2' },
    { key: 'solution.phase2.output3', original: 'Brand-Safe QA', context: 'Solution phase 2 output 3' },
    { key: 'solution.phase3.id', original: 'Phase 3', context: 'Solution phase 3 ID' },
    { key: 'solution.phase3.title', original: 'Scale Decision Layer', context: 'Solution phase 3 title' },
    { key: 'solution.phase3.goal', original: 'Protect your budget and scale only what earns it.', context: 'Solution phase 3 goal' },
    { key: 'solution.phase3.output1', original: 'Creative Scorecard', context: 'Solution phase 3 output 1' },
    { key: 'solution.phase3.output2', original: 'Promote/Kill Rules', context: 'Solution phase 3 output 2' },
    { key: 'solution.phase3.output3', original: 'Validated Creative Plays', context: 'Solution phase 3 output 3' },
    { key: 'solution.outputs.label', original: 'Outputs', context: 'Solution outputs label' },
    { key: 'solution.footer', original: "We're not anti‑creator. We're anti‑improve. We separate what must scale from what must be earned.", context: 'Solution protocol footer line 1' },
    { key: 'solution.footer.line2', original: "We save you from paying for the same lessons again", context: 'Solution protocol footer line 2' },
    { key: 'model.tag', original: 'Operating Model', context: 'Operating model tag' },
    { key: 'model.title', original: 'How Agents Compound Learning', context: 'Operating model title' },
    { key: 'model.description', original: 'We run a simple weekly cadence that turns spend into reusable decisions without slowing your team down.', context: 'Operating model description' },
    { key: 'model.step1.title', original: 'Read the signal', context: 'Operating model step 1 title' },
    { key: 'model.step1.text', original: 'What people watched, clicked, saved.', context: 'Operating model step 1 text' },
    { key: 'model.step2.title', original: 'Pick the test', context: 'Operating model step 2 title' },
    { key: 'model.step2.text', original: 'One hypothesis; one variable.', context: 'Operating model step 2 text' },
    { key: 'model.step3.title', original: 'Ship variants fast', context: 'Operating model step 3 title' },
    { key: 'model.step3.text', original: 'AI accelerates; humans steer taste.', context: 'Operating model step 3 text' },
    { key: 'model.step4.title', original: 'Promote or kill', context: 'Operating model step 4 title' },
    { key: 'model.step4.text', original: 'Winners become Validated Plays.', context: 'Operating model step 4 text' },
    { key: 'model.step5.title', original: 'Write it down', context: 'Operating model step 5 title' },
    { key: 'model.step5.text', original: 'Decision memos update your map.', context: 'Operating model step 5 text' },
    { key: 'model.center.title', original: 'Compound Learning', context: 'Operating model center title' },
    { key: 'model.visual.signal', original: 'Signal', context: 'Operating model visual signal' },
    { key: 'model.visual.memo', original: 'Memo', context: 'Operating model visual memo' },
    { key: 'vs.tag', original: 'Us vs. Them', context: 'Comparison tag' },
    { key: 'vs.title', original: 'Amateurs Guess. Professionals Engineer.', context: 'Comparison title' },
    { key: 'vs.header.feature', original: 'Feature', context: 'Comparison header feature' },
    { key: 'vs.header.old', original: 'Traditional Agency', context: 'Comparison header old' },
    { key: 'vs.header.new', original: 'Creative Intelligence Agents', context: 'Comparison header new' },
    { key: 'vs.row1.feature', original: 'Strategy', context: 'Comparison row 1 feature' },
    { key: 'vs.row1.old', original: 'Hoping for a hit', context: 'Comparison row 1 old' },
    { key: 'vs.row1.new', original: 'Reducing variance with testing', context: 'Comparison row 1 new' },
    { key: 'vs.row2.feature', original: 'Learning', context: 'Comparison row 2 feature' },
    { key: 'vs.row2.old', original: 'Scattered in people\'s heads', context: 'Comparison row 2 old' },
    { key: 'vs.row2.new', original: 'Compounding: Validated Creative Plays', context: 'Comparison row 2 new' },
    { key: 'vs.row3.feature', original: 'Speed', context: 'Comparison row 3 feature' },
    { key: 'vs.row3.old', original: 'Slow briefing cycles', context: 'Comparison row 3 old' },
    { key: 'vs.row3.new', original: 'AI‑accelerated execution in days', context: 'Comparison row 3 new' },
    { key: 'vs.row4.feature', original: 'Measurement', context: 'Comparison row 4 feature' },
    { key: 'vs.row4.old', original: 'Vanity metrics dominate', context: 'Comparison row 4 old' },
    { key: 'vs.row4.new', original: 'Scorecards, gates, and rules', context: 'Comparison row 4 new' },
    { key: 'vs.row5.feature', original: 'Outcome', context: 'Comparison row 5 feature' },
    { key: 'vs.row5.old', original: 'Awareness without clarity', context: 'Comparison row 5 old' },
    { key: 'vs.row5.new', original: 'Decision clarity + repeatable winners', context: 'Comparison row 5 new' },
    { key: 'asset.tag', original: 'The War Chest', context: 'Deliverables tag' },
    { key: 'asset.title', original: 'Don\'t Rent Content. Own the Asset.', context: 'Deliverables title' },
    { key: 'asset.description', original: 'You aren\'t paying for a one‑off service. You\'re acquiring a compounding intelligence asset.', context: 'Deliverables description' },
    { key: 'asset.col1.title', original: 'The Brain', context: 'Deliverables column 1 title' },
    { key: 'asset.col1.sub', original: 'Decision Intelligence', context: 'Deliverables column 1 sub' },
    { key: 'asset.col1.item1', original: 'Customer Decision Intelligence Map', context: 'Deliverables column 1 item 1' },
    { key: 'asset.col1.item2', original: 'Objection Library + Responses', context: 'Deliverables column 1 item 2' },
    { key: 'asset.col1.item3', original: 'Validated Creative Plays Library', context: 'Deliverables column 1 item 3' },
    { key: 'asset.col2.title', original: 'The Fuel', context: 'Deliverables column 2 title' },
    { key: 'asset.col2.sub', original: 'AI-Accelerated Output', context: 'Deliverables column 2 sub' },
    { key: 'asset.col2.item1', original: 'Monthly conversion-first assets', context: 'Deliverables column 2 item 1' },
    { key: 'asset.col2.item2', original: 'Whitelisted access setups', context: 'Deliverables column 2 item 2' },
    { key: 'asset.col2.item3', original: 'Unlimited usage rights', context: 'Deliverables column 2 item 3' },
    { key: 'asset.col3.title', original: 'The Compass', context: 'Deliverables column 3 title' },
    { key: 'asset.col3.sub', original: 'Scale Decisions', context: 'Deliverables column 3 sub' },
    { key: 'asset.col3.item1', original: 'Creative Scorecards', context: 'Deliverables column 3 item 1' },
    { key: 'asset.col3.item2', original: 'Weekly Decision Memos', context: 'Deliverables column 3 item 2' },
    { key: 'asset.col3.item3', original: 'Profit-focused Signal Reports', context: 'Deliverables column 3 item 3' },
    { key: 'timeline.tag', original: 'Risk Removal', context: 'Timeline tag' },
    { key: 'timeline.title', original: 'The First 30 Days', context: 'Timeline title' },
    { key: 'timeline.week1.id', original: 'Week 1', context: 'Timeline week 1 ID' },
    { key: 'timeline.week1.title', original: 'Map & Install', context: 'Timeline week 1 title' },
    { key: 'timeline.week1.desc', original: 'Map the decision + install scorecard rules.', context: 'Timeline week 1 description' },
    { key: 'timeline.week2.id', original: 'Week 2-3', context: 'Timeline week 2-3 ID' },
    { key: 'timeline.week2.title', original: 'Ship & Isolate', context: 'Timeline week 2 title' },
    { key: 'timeline.week2.desc', original: 'Ship fast variants, isolate what works, create Validated Plays.', context: 'Timeline week 2 description' },
    { key: 'timeline.week4.id', original: 'Week 4', context: 'Timeline week 4 ID' },
    { key: 'timeline.week4.title', original: 'Build Scale Plan', context: 'Timeline week 4 title' },
    { key: 'timeline.week4.desc', original: 'What gets budget, what gets killed, what repeats.', context: 'Timeline week 4 description' },
    { key: 'refuse.tag', original: 'What We Refuse', context: 'Credibility tag' },
    { key: 'refuse.item1', original: 'No Content Calendars', context: 'Credibility item 1' },
    { key: 'refuse.item2', original: 'No ROAS without Measurement', context: 'Credibility item 2' },
    { key: 'refuse.item3', original: 'No Deceptive Synths', context: 'Credibility item 3' },
    { key: 'refuse.item4', original: 'No Vanity Views', context: 'Credibility item 4' },
    { key: 'week1.title', original: 'What You Get in Week 1', context: 'Week 1 block title' },
    { key: 'week1.description', original: 'Customer Decision Intelligence Map • Creative Scorecard • Ship/No-Ship Thresholds', context: 'Week 1 block description' },
    { key: 'week1.cta', original: 'Request a redacted sample pack', context: 'Week 1 block CTA' },
    { key: 'final.title', original: 'Stop Restarting. Start Compounding.', context: 'Final CTA title' },
    { key: 'final.description_prefix', original: 'If you want "content," hire an agency. If you want ', context: 'Final CTA description prefix' },
    { key: 'final.description_highlight', original: 'Creative Intelligence AI Agents', context: 'Final CTA description highlight' },
    { key: 'final.description_suffix', original: ' that turn buyer truth into Validated Creative Plays—we should talk.', context: 'Final CTA description suffix' },
    { key: 'final.cta', original: 'Apply for Access', context: 'Final CTA button' },
    { key: 'final.footer', original: 'We\'ll tell you quickly if this is a fit. If not, you leave with clarity.', context: 'Final CTA footer' },
    { key: 'footer.rights', original: 'Digicon Pro. All rights reserved.', context: 'Footer rights' },
  ],
  'book-a-call': [
    { key: 'title', original: 'Book a Call', context: 'Page title' },
    { key: 'description', original: 'Help us understand your needs so we can provide the best solution for your business.', context: 'Page description' },
    { key: 'result.title', original: 'Your Customer Intelligence System Readiness Score', context: 'Result page title' },
  ],
};

export function getPageTexts(pageName: string) {
  return pageTexts[pageName] || [];
}
