// Text extraction utilities for translation

export interface PageTexts {
  [pageName: string]: {
    key: string;
    original: string;
    context?: string;
  }[];
}

export const pageTexts: PageTexts = {
  home: [
    { key: 'header.button', original: 'Customer Intelligence AI Agents', context: 'Header navigation button' },
    { key: 'hero.subtitle1', original: 'Consumer Good', context: 'Hero section subtitle part 1' },
    { key: 'hero.subtitle2', original: 'Brands', context: 'Hero section subtitle part 2' },
    { key: 'hero.title', original: 'Get 1M-100M views in 90 days on social media', context: 'Hero section main title' },
    { key: 'hero.description_prefix', original: 'Backed by our Viral Content Research Lab, the system behind over ', context: 'Hero section description prefix' },
    { key: 'hero.views', original: '6 billion views', context: 'Hero section views count' },
    { key: 'hero.description_mid', original: ' and ', context: 'Hero section description middle' },
    { key: 'hero.followers', original: '24 million followers', context: 'Hero section followers count' },
    { key: 'hero.cta', original: 'Dominate Social Media', context: 'Hero call-to-action button' },
    { key: 'video.alt', original: 'Digicon Pro Showreel 2025 Video Thumbnail', context: 'Video thumbnail alt text' },
    { key: 'video.title', original: 'Digicon Pro Showreel 2025 Video', context: 'Video iframe title' },
    { key: 'value.title_prefix', original: 'Use maximum content distribution to ', context: 'Value title prefix' },
    { key: 'value.title_highlight', original: ' dominate social media', context: 'Value title highlight' },
    { key: 'value.stat1.val', original: '1/25th', context: 'Value stat 1 value' },
    { key: 'value.stat1.label', original: 'Cost of Ads', context: 'Value stat 1 label' },
    { key: 'value.stat2.val', original: 'Limited', context: 'Value stat 2 value' },
    { key: 'value.stat2.label', original: 'Spots', context: 'Value stat 2 label' },
    { key: 'value.stat3.val', original: 'Fully', context: 'Value stat 3 value' },
    { key: 'value.stat3.label', original: 'Compliant', context: 'Value stat 3 label' },
    { key: 'value.stats.prefix', original: "We've generated over ", context: 'Value stats prefix' },
    { key: 'value.stats.views_count', original: '6 billion organic views ', context: 'Value stats views count' },
    { key: 'value.stats.suffix', original: ' in less than 2 years with our proprietary Viral Content Research Lab.', context: 'Value stats suffix' },
    { key: 'value.listTitle', original: 'Work with us to:', context: 'Value proposition list title' },
    { key: 'value.item1', original: 'Have the fastest way to grow on social media today', context: 'Value proposition item 1' },
    { key: 'value.item2', original: 'Scale brands to post 100+ times per month', context: 'Value proposition item 2' },
    { key: 'value.item3', original: 'Get in front of millions more of the right people', context: 'Value proposition item 3' },
    { key: 'value.item4', original: 'Ensure top-quality across all the content posted', context: 'Value proposition item 4' },
    { key: 'value.cta', original: 'Talk to us', context: 'Value section CTA button' },
    { key: 'showcase.title_prefix', original: "(Just some) content we've ", context: 'Showcase title prefix' },
    { key: 'showcase.title_highlight', original: 'created', context: 'Showcase title highlight' },
    { key: 'problem.title_prefix', original: 'Most consumer good brands are generating a ', context: 'Problem title prefix' },
    { key: 'problem.title_highlight', original: ' small fraction', context: 'Problem title highlight' },
    { key: 'problem.title_suffix', original: ' of the potential growth from their organic content.', context: 'Problem title suffix' },
    { key: 'problem.subtitle', original: '(Even if you already have an audience in the millions)', context: 'Problem section subtitle' },
    { key: 'problem.description', original: 'This results in dramatically less exposure and growth for your brand.', context: 'Problem section description' },
    { key: 'problem.cta_text', original: 'You deserve more for your efforts.', context: 'Problem section CTA text' },
    { key: 'brands.title_prefix', original: 'Brands that have ', context: 'Brands title prefix' },
    { key: 'brands.title_highlight', original: 'grown', context: 'Brands title highlight' },
    { key: 'brands.title_suffix', original: ' with us', context: 'Brands title suffix' },
    { key: 'recognition.title_prefix', original: 'Recognized by ', context: 'Recognition title prefix' },
    { key: 'recognition.title_highlight', original: 'publications ', context: 'Recognition title highlight' },
    { key: 'recognition.title_suffix', original: ' as the #1 leading firm in social media growth', context: 'Recognition title suffix' },
    { key: 'how.title_prefix', original: 'How does it ', context: 'How title prefix' },
    { key: 'how.title_highlight', original: 'work?', context: 'How title highlight' },
    { key: 'how.subtitle_prefix', original: 'Data-driven success formula discovery through our ', context: 'How subtitle prefix' },
    { key: 'how.subtitle_highlight', original: '"Viral Content Research Lab"', context: 'How subtitle highlight' },
    { key: 'how.step1.title', original: 'Idea Generation', context: 'How it works step 1 title' },
    { key: 'how.step1.desc', original: 'We analyze the latest TikTok trends, Gen Z interests, and competitor content daily to create a constant source of fresh ideas.', context: 'How it works step 1 description' },
    { key: 'how.step2.title', original: 'Rapid Testing', context: 'How it works step 2 title' },
    { key: 'how.step2.desc', original: 'Generated ideas are uploaded to private test channels to gauge immediate consumer reactions and feedback.', context: 'How it works step 2 description' },
    { key: 'how.step3.title', original: 'Data Validation', context: 'How it works step 3 title' },
    { key: 'how.step3.desc', original: 'We objectively determine \'success\' and \'failure\' using clear metrics: views, comments, and share rates.', context: 'How it works step 3 description' },
    { key: 'how.step4.title', original: 'Success Formula Scaling', context: 'How it works step 4 title' },
    { key: 'how.step4.desc', original: 'We intensively utilize the format and key elements of verified \'hit videos\' to maximize viral impact.', context: 'How it works step 4 description' },
    { key: 'how.approach.title', original: 'Our Proven Approach', context: 'Proven approach section title' },
    { key: 'how.approach.item1.title', original: 'Minimize uncertainty', context: 'Proven approach item 1 title' },
    { key: 'how.approach.item1.desc', original: ' and execute only the highest probability marketing strategies', context: 'Proven approach item 1 description' },
    { key: 'how.approach.item2.title', original: 'Collect feedback', context: 'Proven approach item 2 title' },
    { key: 'how.approach.item2.desc', original: ' from small target groups and analyze rapidly', context: 'Proven approach item 2 description' },
    { key: 'how.approach.item3.title', original: 'Repeatedly apply', context: 'Proven approach item 3 title' },
    { key: 'how.approach.item3.desc', original: ' verified success formulas to maximize marketing efficiency', context: 'Proven approach item 3 description' },
    { key: 'how.compliance_prefix', original: 'Yes, this is ', context: 'Compliance prefix' },
    { key: 'how.compliance_highlight', original: 'fully compliant ', context: 'Compliance highlight' },
    { key: 'how.compliance_suffix', original: 'across each social media platform.', context: 'Compliance suffix' },
    { key: 'results.title_prefix', original: "Results we've ", context: 'Results title prefix' },
    { key: 'results.title_highlight', original: 'generated', context: 'Results title highlight' },
    { key: 'results.stat1.val', original: '6B+', context: 'Results stat 1 value' },
    { key: 'results.stat1.desc', original: 'Views generated on social platforms', context: 'Results stat 1 description' },
    { key: 'results.stat2.val', original: '24M+', context: 'Results stat 2 value' },
    { key: 'results.stat2.desc', original: 'Followers gained for our clients', context: 'Results stat 2 description' },
    { key: 'results.stat3.val', original: '137M+', context: 'Results stat 3 value' },
    { key: 'results.stat3.desc', original: 'Followers reached through top brands', context: 'Results stat 3 description' },
    { key: 'results.stat4.val', original: '20,300+', context: 'Results stat 4 value' },
    { key: 'results.stat4.desc', original: 'Pieces of content published per month', context: 'Results stat 4 description' },
    { key: 'results.stat5.val', original: '85+', context: 'Results stat 5 value' },
    { key: 'results.stat5.desc', original: 'Expert team members', context: 'Results stat 5 description' },
    { key: 'results.stat6.val', original: '450+', context: 'Results stat 6 value' },
    { key: 'results.stat6.desc', original: 'Years of combined experience', context: 'Results stat 6 description' },
    { key: 'results.cta_text', original: 'Want to learn if we are a fit to scale your brand?', context: 'Results section CTA text' },
    { key: 'platforms.title_prefix', original: 'Become ', context: 'Platforms title prefix' },
    { key: 'platforms.title_highlight', original: 'omnipresent', context: 'Platforms title highlight' },
    { key: 'platforms.title_suffix', original: ' on our expert platforms', context: 'Platforms title suffix' },
    { key: 'platforms.cta_text', original: 'Want to learn more?', context: 'Platforms section CTA text' },
    { key: 'footer.cta', original: 'Ready to dominate social media?', context: 'Footer CTA text' },
    { key: 'footer.rights_prefix', original: '© ', context: 'Footer copyright prefix' },
    { key: 'footer.rights_suffix', original: ' Digicon Pro. All rights reserved.', context: 'Footer copyright suffix' },
  ],
  'creative-intelligence-agent': [
    { key: 'header.button', original: 'Visibility Scaling AI Agents', context: 'Header navigation button' },
    { key: 'hero.tag', original: 'Creative Intelligence Agents', context: 'Hero section tag' },
    { key: 'hero.title', original: 'Stop Paying Influencers to Improvise. Build Agents You Own.', context: 'Hero section main title' },
    { key: 'hero.subtitle', original: 'We deploy Creative Intelligence AI Agents that mine your first‑party data, ship controlled creative variants fast, and convert winners into Validated Creative Plays you can scale.', context: 'Hero section subtitle' },
    { key: 'hero.cta1', original: 'Apply for Access', context: 'Primary CTA button' },
    { key: 'hero.cta2', original: 'See how it works', context: 'Secondary CTA button' },
    { key: 'social.revenue.impact', original: 'Revenue Impact', context: 'Social proof revenue impact' },
    { key: 'social.revenue.sub', original: 'Attributed via optimization', context: 'Social proof revenue impact sub' },
    { key: 'social.organic.views', original: 'Organic Views', context: 'Social proof organic views' },
    { key: 'social.organic.sub', original: 'Across social media', context: 'Social proof organic views sub' },
    { key: 'social.adspend.managed', original: 'Ad Spend Managed', context: 'Social proof ad spend managed' },
    { key: 'social.adspend.sub', original: 'Optimized by our team', context: 'Social proof ad spend managed sub' },
    { key: 'social.campaigns.title', original: 'Campaigns', context: 'Social proof campaigns title' },
    { key: 'social.campaigns.sub', original: 'Successful launches', context: 'Social proof campaigns sub' },
    { key: 'fit.tag', original: 'Fit Filter', context: 'Fit filter tag' },
    { key: 'fit.title', original: 'Who This Is For (and Who It\'s Not)', context: 'Fit filter title' },
    { key: 'fit.for.title', original: 'For Leaders Who Want:', context: 'Fit filter for title' },
    { key: 'fit.for.item1', original: 'Brands investing consistently in paid + creators who want repeatable wins', context: 'Fit filter for item 1' },
    { key: 'fit.for.item2', original: 'Teams that care about speed, but refuse to sacrifice trust', context: 'Fit filter for item 2' },
    { key: 'fit.for.item3', original: 'Leaders who want learning that compounds', context: 'Fit filter for item 3' },
    { key: 'fit.not.title', original: 'Not For:', context: 'Fit filter not for title' },
    { key: 'fit.not.item1', original: '"Content calendars" with no testing discipline', context: 'Fit filter not for item 1' },
    { key: 'fit.not.item2', original: 'Anyone looking for "AI volume" without measurement rules', context: 'Fit filter not for item 2' },
    { key: 'fit.not.item3', original: 'Trust‑sensitive categories that want deceptive synthetic endorsements', context: 'Fit filter not for item 3' },
    { key: 'problem.tag', original: 'The Problem', context: 'Problem section tag' },
    { key: 'problem.title', original: 'The "Creativity Gap" Is Quietly Taxing Every Campaign You Run.', context: 'Problem section title' },
    { key: 'problem.description', original: 'Visibility used to come from people. Now it comes from the feed. When brands outsource creative direction without capturing learnings, they keep paying for the same lessons again and again.', context: 'Problem section description' },
    { key: 'problem.item1.title', original: 'Too Many Messages', context: 'Problem item 1 title' },
    { key: 'problem.item1.desc', original: 'Diluted core value proposition.', context: 'Problem item 1 description' },
    { key: 'problem.item2.title', original: 'Too Little Truth', context: 'Problem item 2 title' },
    { key: 'problem.item2.desc', original: 'Content that feels like \'ads\' gets skipped.', context: 'Problem item 2 description' },
    { key: 'problem.item3.title', original: 'High Variance', context: 'Problem item 3 title' },
    { key: 'problem.item3.desc', original: 'No system to turn outcomes into decisions.', context: 'Problem item 3 description' },
    { key: 'problem.footer', original: 'We\'re not anti‑creator. We\'re anti‑improv. We separate what must scale from what must be earned.', context: 'Problem footer text' },
    { key: 'solution.tag', original: 'The Protocol', context: 'Solution protocol tag' },
    { key: 'solution.title', original: 'How Our AI Agents Turn Data Into Validated Creative Plays', context: 'Solution protocol title' },
    { key: 'solution.phase1.id', original: 'Phase 1', context: 'Solution phase 1 ID' },
    { key: 'solution.phase1.title', original: 'Customer Decision Intelligence Map', context: 'Solution phase 1 title' },
    { key: 'solution.phase1.goal', original: 'Know what makes your customer act before you scale.', context: 'Solution phase 1 goal' },
    { key: 'solution.phase1.output1', original: 'Market Message Map', context: 'Solution phase 1 output 1' },
    { key: 'solution.phase1.output2', original: 'Objection Library', context: 'Solution phase 1 output 2' },
    { key: 'solution.phase1.output3', original: 'First Hypothesis Set', context: 'Solution phase 1 output 3' },
    { key: 'solution.phase2.id', original: 'Phase 2', context: 'Solution phase 2 ID' },
    { key: 'solution.phase2.title', original: 'AI‑Accelerated Throughput Engine', context: 'Solution phase 2 title' },
    { key: 'solution.phase2.goal', original: 'Produce enough high-quality variants to learn fast.', context: 'Solution phase 2 goal' },
    { key: 'solution.phase2.output1', original: 'Monthly Creative Cadence', context: 'Solution phase 2 output 1' },
    { key: 'solution.phase2.output2', original: 'Whitelisting Setups', context: 'Solution phase 2 output 2' },
    { key: 'solution.phase2.output3', original: 'Brand-Safe QA', context: 'Solution phase 2 output 3' },
    { key: 'solution.phase3.id', original: 'Phase 3', context: 'Solution phase 3 ID' },
    { key: 'solution.phase3.title', original: 'Scale Decision Layer', context: 'Solution phase 3 title' },
    { key: 'solution.phase3.goal', original: 'Protect your budget and scale only what earns it.', context: 'Solution phase 3 goal' },
    { key: 'solution.phase3.output1', original: 'Creative Scorecard', context: 'Solution phase 3 output 1' },
    { key: 'solution.phase3.output2', original: 'Promote/Kill Rules', context: 'Solution phase 3 output 2' },
    { key: 'solution.phase3.output3', original: 'Validated Creative Plays', context: 'Solution phase 3 output 3' },
    { key: 'solution.outputs.label', original: 'Outputs', context: 'Solution outputs label' },
    { key: 'model.tag', original: 'Operating Model', context: 'Operating model tag' },
    { key: 'model.title', original: 'How Agents Compound Learning', context: 'Operating model title' },
    { key: 'model.description', original: 'We run a simple weekly cadence that turns spend into reusable decisions without slowing your team down.', context: 'Operating model description' },
    { key: 'model.step1.title', original: 'Read the signal', context: 'Operating model step 1 title' },
    { key: 'model.step1.text', original: 'What people watched, clicked, saved.', context: 'Operating model step 1 text' },
    { key: 'model.step2.title', original: 'Pick the test', context: 'Operating model step 2 title' },
    { key: 'model.step2.text', original: 'One hypothesis; one variable.', context: 'Operating model step 2 text' },
    { key: 'model.step3.title', original: 'Ship variants fast', context: 'Operating model step 3 title' },
    { key: 'model.step3.text', original: 'AI accelerates; humans steer taste.', context: 'Operating model step 3 text' },
    { key: 'model.step4.title', original: 'Promote or kill', context: 'Operating model step 4 title' },
    { key: 'model.step4.text', original: 'Winners become Validated Plays.', context: 'Operating model step 4 text' },
    { key: 'model.step5.title', original: 'Write it down', context: 'Operating model step 5 title' },
    { key: 'model.step5.text', original: 'Decision memos update your map.', context: 'Operating model step 5 text' },
    { key: 'model.center.title', original: 'Compound Learning', context: 'Operating model center title' },
    { key: 'model.visual.signal', original: 'Signal', context: 'Operating model visual signal' },
    { key: 'model.visual.memo', original: 'Memo', context: 'Operating model visual memo' },
    { key: 'vs.tag', original: 'Us vs. Them', context: 'Comparison tag' },
    { key: 'vs.title', original: 'Amateurs Guess. Professionals Engineer.', context: 'Comparison title' },
    { key: 'vs.header.feature', original: 'Feature', context: 'Comparison header feature' },
    { key: 'vs.header.old', original: 'Traditional Agency', context: 'Comparison header old' },
    { key: 'vs.header.new', original: 'Creative Intelligence Agents', context: 'Comparison header new' },
    { key: 'vs.row1.feature', original: 'Strategy', context: 'Comparison row 1 feature' },
    { key: 'vs.row1.old', original: 'Hoping for a hit', context: 'Comparison row 1 old' },
    { key: 'vs.row1.new', original: 'Reducing variance with testing', context: 'Comparison row 1 new' },
    { key: 'vs.row2.feature', original: 'Learning', context: 'Comparison row 2 feature' },
    { key: 'vs.row2.old', original: 'Scattered in people\'s heads', context: 'Comparison row 2 old' },
    { key: 'vs.row2.new', original: 'Compounding: Validated Creative Plays', context: 'Comparison row 2 new' },
    { key: 'vs.row3.feature', original: 'Speed', context: 'Comparison row 3 feature' },
    { key: 'vs.row3.old', original: 'Slow briefing cycles', context: 'Comparison row 3 old' },
    { key: 'vs.row3.new', original: 'AI‑accelerated execution in days', context: 'Comparison row 3 new' },
    { key: 'vs.row4.feature', original: 'Measurement', context: 'Comparison row 4 feature' },
    { key: 'vs.row4.old', original: 'Vanity metrics dominate', context: 'Comparison row 4 old' },
    { key: 'vs.row4.new', original: 'Scorecards, gates, and rules', context: 'Comparison row 4 new' },
    { key: 'vs.row5.feature', original: 'Outcome', context: 'Comparison row 5 feature' },
    { key: 'vs.row5.old', original: 'Awareness without clarity', context: 'Comparison row 5 old' },
    { key: 'vs.row5.new', original: 'Decision clarity + repeatable winners', context: 'Comparison row 5 new' },
    { key: 'asset.tag', original: 'The War Chest', context: 'Deliverables tag' },
    { key: 'asset.title', original: 'Don\'t Rent Content. Own the Asset.', context: 'Deliverables title' },
    { key: 'asset.description', original: 'You aren\'t paying for a one‑off service. You\'re acquiring a compounding intelligence asset.', context: 'Deliverables description' },
    { key: 'asset.col1.title', original: 'The Brain', context: 'Deliverables column 1 title' },
    { key: 'asset.col1.sub', original: 'Decision Intelligence', context: 'Deliverables column 1 sub' },
    { key: 'asset.col1.item1', original: 'Customer Decision Intelligence Map', context: 'Deliverables column 1 item 1' },
    { key: 'asset.col1.item2', original: 'Objection Library + Responses', context: 'Deliverables column 1 item 2' },
    { key: 'asset.col1.item3', original: 'Validated Creative Plays Library', context: 'Deliverables column 1 item 3' },
    { key: 'asset.col2.title', original: 'The Fuel', context: 'Deliverables column 2 title' },
    { key: 'asset.col2.sub', original: 'AI-Accelerated Output', context: 'Deliverables column 2 sub' },
    { key: 'asset.col2.item1', original: 'Monthly conversion-first assets', context: 'Deliverables column 2 item 1' },
    { key: 'asset.col2.item2', original: 'Whitelisted access setups', context: 'Deliverables column 2 item 2' },
    { key: 'asset.col2.item3', original: 'Unlimited usage rights', context: 'Deliverables column 2 item 3' },
    { key: 'asset.col3.title', original: 'The Compass', context: 'Deliverables column 3 title' },
    { key: 'asset.col3.sub', original: 'Scale Decisions', context: 'Deliverables column 3 sub' },
    { key: 'asset.col3.item1', original: 'Creative Scorecards', context: 'Deliverables column 3 item 1' },
    { key: 'asset.col3.item2', original: 'Weekly Decision Memos', context: 'Deliverables column 3 item 2' },
    { key: 'asset.col3.item3', original: 'Profit-focused Signal Reports', context: 'Deliverables column 3 item 3' },
    { key: 'timeline.tag', original: 'Risk Removal', context: 'Timeline tag' },
    { key: 'timeline.title', original: 'The First 30 Days', context: 'Timeline title' },
    { key: 'timeline.week1.id', original: 'Week 1', context: 'Timeline week 1 ID' },
    { key: 'timeline.week1.title', original: 'Map & Install', context: 'Timeline week 1 title' },
    { key: 'timeline.week1.desc', original: 'Map the decision + install scorecard rules.', context: 'Timeline week 1 description' },
    { key: 'timeline.week2.id', original: 'Week 2-3', context: 'Timeline week 2-3 ID' },
    { key: 'timeline.week2.title', original: 'Ship & Isolate', context: 'Timeline week 2 title' },
    { key: 'timeline.week2.desc', original: 'Ship fast variants, isolate what works, create Validated Plays.', context: 'Timeline week 2 description' },
    { key: 'timeline.week4.id', original: 'Week 4', context: 'Timeline week 4 ID' },
    { key: 'timeline.week4.title', original: 'Build Scale Plan', context: 'Timeline week 4 title' },
    { key: 'timeline.week4.desc', original: 'What gets budget, what gets killed, what repeats.', context: 'Timeline week 4 description' },
    { key: 'refuse.tag', original: 'What We Refuse', context: 'Credibility tag' },
    { key: 'refuse.item1', original: 'No Content Calendars', context: 'Credibility item 1' },
    { key: 'refuse.item2', original: 'No ROAS without Measurement', context: 'Credibility item 2' },
    { key: 'refuse.item3', original: 'No Deceptive Synths', context: 'Credibility item 3' },
    { key: 'refuse.item4', original: 'No Vanity Views', context: 'Credibility item 4' },
    { key: 'week1.title', original: 'What You Get in Week 1', context: 'Week 1 block title' },
    { key: 'week1.description', original: 'Customer Decision Intelligence Map • Creative Scorecard • Ship/No-Ship Thresholds', context: 'Week 1 block description' },
    { key: 'week1.cta', original: 'Request a redacted sample pack', context: 'Week 1 block CTA' },
    { key: 'final.title', original: 'Stop Restarting. Start Compounding.', context: 'Final CTA title' },
    { key: 'final.description_prefix', original: 'If you want "content," hire an agency. If you want ', context: 'Final CTA description prefix' },
    { key: 'final.description_highlight', original: 'Creative Intelligence AI Agents', context: 'Final CTA description highlight' },
    { key: 'final.description_suffix', original: ' that turn buyer truth into Validated Creative Plays—we should talk.', context: 'Final CTA description suffix' },
    { key: 'final.cta', original: 'Apply for Access', context: 'Final CTA button' },
    { key: 'final.footer', original: 'We\'ll tell you quickly if this is a fit. If not, you leave with clarity.', context: 'Final CTA footer' },
    { key: 'footer.rights', original: 'Digicon Pro. All rights reserved.', context: 'Footer rights' },
  ],
  'book-a-call': [
    { key: 'title', original: 'Book a Call', context: 'Page title' },
    { key: 'description', original: 'Help us understand your needs so we can provide the best solution for your business.', context: 'Page description' },
    { key: 'result.title', original: 'Your Customer Intelligence System Readiness Score', context: 'Result page title' },
  ],
};

export function getPageTexts(pageName: string) {
  return pageTexts[pageName] || [];
}
